Repository CA21engineer/morning-weakers, pull requests merged in 2020-06, with the labels that each got.

#1 gitignoreが反映されてないのを修正 & .idea/codeStyles/をignore
  .dart_tool/package_config.json
  .gitignore
  .idea/codeStyles/Project.xml
  .idea/libraries/Dart_Packages.xml
  .idea/libraries/Dart_SDK.xml
  .idea/libraries/Flutter_Plugins.xml
  .packages
Labels: invalid

#11 implement base input profile page
  lib/pages/new_profile/new_profile_page.dart
Labels: enhancement

#29 fix to reflect gitignore about .idea/modules.xml
  .idea/modules.xml
Labels: invalid

#28 管理者画面Top作成
  lib/app.dart
  lib/pages/admin_top/admin_top_page.dart
  lib/pages/admin_top/widgets/list_container.dart
  lib/pages/all/all_page.dart
Labels: enhancement

#46 ProfileDetailPageのlogic
  lib/extensions/list.dart
  lib/models/technical_stack/language.dart
  lib/models/technical_stack/stack.dart
  lib/pages/profile_detail/profile_detail_controller.dart
  lib/pages/profile_detail/profile_detail_page.dart
  lib/pages/profile_detail/profile_detail_state.dart
  lib/pages/profile_detail/profile_detail_state.freezed.dart
  lib/pages/profile_detail/widgets/profile_container.dart
  lib/pages/profile_detail/widgets/profile_list_container.dart
  lib/pages/profile_detail/widgets/technical_stack_container.dart
Labels: enhancement

#44 ログイン・新規登録の作成
  .idea/dictionaries/dictionary.xml
  assets/images/btn_google_signin/dark/disabled.png
  assets/images/btn_google_signin/dark/focus.png
  assets/images/btn_google_signin/dark/normal.png
  assets/images/btn_google_signin/dark/pressed.png
  assets/images/btn_google_signin/light/disabled.png
  assets/images/btn_google_signin/light/focus.png
  assets/images/btn_google_signin/light/normal.png
  assets/images/btn_google_signin/light/pressed.png
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/app.dart
  lib/pages/all/all_page.dart
  lib/pages/input_participant_info/input_participant_info_page.dart
  lib/pages/login/login_next_page.dart
  lib/pages/login/login_page.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#50 HomePageのロジックを組んだ
  lib/core/dummy_data.dart
  lib/extensions/enum.dart
  lib/models/group/group.dart
  lib/models/group/group.freezed.dart
  lib/models/group/group.g.dart
  lib/pages/home/data/data_table_model.dart
  lib/pages/home/data/data_table_model.freezed.dart
  lib/pages/home/home_controller.dart
  lib/pages/home/home_page.dart
  lib/pages/home/home_state.dart
  lib/pages/home/home_state.freezed.dart
  lib/pages/home/widget/data_table.dart
  lib/pages/home/widget/source_link_widget.dart
Labels: enhancement

#54 グループ作成画面のUIのみ
  lib/app.dart
  lib/models/technical_stack/language.dart
  lib/models/technical_stack/stack.dart
  lib/models/technical_stack/technical_stack.dart
  lib/pages/admin_group_edit/admin_group_edit_page.dart
  lib/pages/admin_group_edit/widgets/admin_group_edit_container.dart
  lib/pages/admin_group_edit/widgets/one_team_number_container.dart
  lib/pages/admin_group_edit/widgets/total_number_container.dart
  lib/pages/admin_group_edit/widgets/user_list_container.dart
  lib/pages/all/all_page.dart
  lib/pages/profile_detail/profile_detail_controller.dart
  lib/pages/profile_detail/widgets/technical_stack_container.dart
Labels: enhancement

#69 グループ分けのロジック
  lib/models/participant/participant.dart
Labels: enhancement

#43 HackathonRepositoryの実装
  .github/workflows/build_workflow.yml
  .idea/dictionaries/dictionary.xml
  android/app/build.gradle
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/app.dart
  lib/core/dummy_data.dart
  lib/models/converter/converters.dart
  lib/models/converter/group_converter.dart
  lib/models/converter/link_converter.dart
  lib/models/converter/notification_converter.dart
  lib/models/converter/participant_converter.dart
  lib/models/converter/questionnaire_converter.dart
  lib/models/converter/schedule_candidate_converter.dart
  lib/models/converter/technical_stack_converter.dart
  lib/models/converter/user_converter.dart
  lib/models/group/group.dart
  lib/models/group/group.freezed.dart
  lib/models/group/group.g.dart
  lib/models/hackathon/hackathon.dart
  lib/models/hackathon/hackathon.freezed.dart
  lib/models/hackathon/hackathon.g.dart
  lib/models/joined/joined.dart
  lib/models/joined/joined.freezed.dart
  lib/models/joined/joined.g.dart
  lib/models/notification/notification.dart
  lib/models/notification/notification.freezed.dart
  lib/models/notification/notification.g.dart
  lib/models/participant/participant.dart
  lib/models/participant/participant.freezed.dart
  lib/models/participant/participant.g.dart
  lib/models/questionnaire/questionnaire.dart
  lib/models/questionnaire/questionnaire.freezed.dart
  lib/models/questionnaire/questionnaire.g.dart
  lib/models/technical_stack/technical_stack.g.dart
  lib/models/user/user.dart
  lib/models/user/user.freezed.dart
  lib/models/user/user.g.dart
  lib/pages/home/widget/source_link_widget.dart
  lib/pages/state_notifier_sample/state_notifier_sample_controller.dart
  lib/pages/state_notifier_sample/state_notifier_sample_page.dart
  lib/pages/state_notifier_sample/state_notifier_sample_state.dart
  lib/pages/state_notifier_sample/state_notifier_sample_state.freezed.dart
  lib/repositories/group_repository.dart
  lib/repositories/hackathon_repository.dart
  lib/repositories/notification_repository.dart
  lib/repositories/participant_repository.dart
  lib/repositories/questionnaire_repository.dart
  lib/repository/hackathon_repository.dart
Labels: WIP

#84 ハッカソン概要画面作成の全て
  lib/app.dart
  lib/models/participant/participant.dart
  lib/models/participant/participant.freezed.dart
  lib/pages/admin_input_hackathon_info/admin_input_hackathon_info_controller.dart
  lib/pages/admin_input_hackathon_info/admin_input_hackathon_info_page.dart
  lib/pages/admin_input_hackathon_info/admin_input_hackathon_info_state.dart
  lib/pages/admin_input_hackathon_info/admin_input_hackathon_info_state.freezed.dart
  lib/pages/admin_input_hackathon_info/widgets/admin_input_hackathon_info_container.dart
  lib/pages/admin_input_hackathon_info/widgets/date_list_container.dart
  lib/pages/admin_input_hackathon_info/widgets/text_input_container.dart
  lib/pages/all/all_page.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#93 グループ名をプロパティに格納
  lib/models/participant/participant.dart
  lib/pages/admin_group_edit/widgets/admin_group_edit_container.dart
  lib/pages/admin_group_edit/widgets/user_lists_container.dart
  lib/pages/admin_input_hackathon_info/widgets/admin_input_hackathon_info_container.dart
Labels: enhancement

#96 modify: put repository in controller
  lib/pages/admin_input_hackathon_info/admin_input_hackathon_info_controller.dart
Labels: enhancement

#97 modify: put repository in controller
  lib/pages/admin_group_edit/admin_group_edit_controller.dart
  lib/pages/admin_input_hackathon_info/admin_input_hackathon_info_controller.dart
  lib/pages/profile_detail/profile_detail_controller.dart
Labels: enhancement
